version: '3.9'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
