FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

WORKDIR /app/backend
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
